### ISSUE TITLE
Nothing Serious (Release)

### ISSUE THREAD

**Issue by turismo444** [svbnet/Athame#10]
Inturrupted the download, though the title download worked after retrying
![unbenannt](https://cloud.githubusercontent.com/assets/17822754/24918845/186d5b94-1ee2-11e7-9fb4-12da3fecf780.PNG)

**Comment by jonaaa20** [comment]
"Is not ready for playback"

Not available on your country.

**Comment by svbnet** [comment]
That's odd. Can you post the playlist URL in this thread? Usually tracks that are unable to be played back will be unselectable in the download queue, since Tidal indicates that they aren't available in the metadata returned.

**Comment by turismo444** [comment]
sure!:
https://listen.tidal.com/playlist/2e063f6a-353f-4335-8ad8-05e72f15b87f

**Comment by svbnet** [comment]
Seems to be an issue on Tidal's side, since Athame will never download a track that Tidal says is not downloadable. Unfortunately I can't seem to reproduce it, since it allows streaming on web and in Athame. Is the item greyed out/unplayable when you view it on web?

**Comment by turismo444** [comment]
No actually, it was just a problem for a moment. After i retried to downlod on the same track, it worked immediately

Am 13.04.2017 um 01:26 schrieb Joe <notifications@github.com<mailto:notifications@github.com>>:


Seems to be an issue on Tidal's side, since Athame will never download a track that Tidal says is not downloadable. Unfortunately I can't seem to reproduce it, since it allows streaming on web and in Athame. Is the item greyed out/unplayable when you view it on web?

**Comment by hjtech** [comment]
I'm having the same error, it seems that Tidal is somehow preventing the playback or timing out after a specific amount of downloads. After the error, if I try to play a song via web or via the Tidal app, it doesn't play. I usually need to wait few minutes to retry and then it works, the problem is that I'm forced to close and reopen the Athame or remove the playlist manually, and if the song in the playlist was already downloaded, it gives another error.

If this is on Tidal's end, it would be helpful to allow Athame to idle after X number of downloads.

**Comment by svbnet** [comment]
I can't seem to reproduce it, unfortunately. If possible,

* What is your subscription type and quality setting?
* Does this happen for lossy downloads on a lossless quality (i.e. if you are expecting a FLAC file but an M4A one is downloaded instead)?
* Does this happen when more than one media collection (i.e. added URL) is in the queue?

You could also try using the `streamUrl` API call instead (Menu > Settings > Services > Tidal > untick "Use offlineUrl" option).

**Comment by turismo444** [comment]
In my specific case:
1. HIFI in Trial month
2. No, was downloading on 320, not on flac
3. no, just one playlist was beeing downloded at the time

**Comment by hjtech** [comment]
- Paid HIFI
- I'm only downloading FLAC
- Happens only with large collections

I noticed I was using version 0.3.2 and not 0.4. I'm now using the latest version and so far I have received one error, way less than before. However, I'm now getting the following error while adding a playlist:
`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Athame.Utils.TrackFileExtensions.<>c.<GetBasicPath>b__1_0(Object o)
   at Athame.Utils.StringObjectFormatter.<>c__DisplayClass4_0.<Format>b__1(Match match)
   at System.Text.RegularExpressions.RegexReplacement.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at Athame.Utils.StringObjectFormatter.Format(String formatString, Object value, Func`2 stringFormatter)
   at Athame.Utils.TrackFileExtensions.GetBasicPath(Track track, String pathFormat)
   at Athame.UI.MainForm.AddToQueue(MusicService service, IMediaCollection item, String pathFormat)
   at Athame.UI.MainForm.<>c__DisplayClass40_0.<<button1_Click>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1637.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Athame
    Assembly Version: 0.4.0.0
    Win32 Version: 0.4.0.0
    CodeBase: file:///C:/Users/User/Desktop/athame-0.4/Athame.exe
----------------------------------------
Athame.PluginAPI
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/User/Desktop/athame-0.4/Athame.PluginAPI.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1637.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.1.19813
    CodeBase: file:///C:/Users/User/Desktop/athame-0.4/Newtonsoft.Json.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1638.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1637.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1636.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
GoogleMusicApi
    Assembly Version: 1.0.33.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/User/Desktop/athame-0.4/GoogleMusicApi.DLL
----------------------------------------
OpenTidl
    Assembly Version: 1.10.2.0
    Win32 Version: 1.10.2.0
    CodeBase: file:///C:/Users/User/Desktop/athame-0.4/OpenTidl.DLL
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Users/User/Desktop/athame-0.4/Microsoft.WindowsAPICodePack.Shell.DLL
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Users/User/Desktop/athame-0.4/Microsoft.WindowsAPICodePack.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1637.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1637.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.`

**Comment by zakatov** [comment]
I have a question about google play music.

When I change the quality of Google Play music 320/160/128, it's all downloaded 160.

**Comment by sucks-at-the-computers** [comment]
Guys. I'm extra new to programming. I've never used Visual Studio. I've downloaded the Athame Tidal Plugin, Visual Studio 2017, as well as .NET 4.7. I'm just confused as to what comes next. I have a tidal subscription, I generally use the web player but I also have the desktop install as well. I know this comes off as noob-status, but I could really use some guidance on how to initiate these downloads.

**Comment by svbnet** [comment]
If you just want to use it, just look at the releases tab up the top where you can download a built version.
