### ISSUE TITLE
Precautions from DCMA

### ISSUE THREAD

**Issue by m0rpheaux** [svbnet/Athame#100]
Will there be anything like this precaution for Athame from DCMA takedowns ?
https://github.com/J05HI/DeezLoadr/issues/67

**Comment by J05HI** [comment]
I think no :(

**Comment by TripleFrequency** [comment]
Athame itself can't legally be removed via DMCA take-down. An individual plugin possibly could, depending on how they access various APIs and the likes, but Athame hosts no content, and accesses no illegal content in any way.

**Comment by J05HI** [comment]
@TripleFrequency
Yeah thats good but if a plugin gets fucked..

**Comment by ThePlayingGoblin** [comment]
This reminds me of the asshole who snitched about deezloader only because the community became private. Let's hope this doesn't happen again with the Tidal and Deezer plugins for athame.

**Comment by J05HI** [comment]
@ThePlayingGoblin 
I can guarantee that this won't happen with DeezLoadr :)

**Comment by fabriccioguzman** [comment]
Currently deezloader and its community does not exist in reddit the developer ParadoxalManiak abandoned the project and left it in charge to upploader of boerse.to but you can only access what they live in Germany when registering, but when registering in that forum in another country that is not germany, the sub-content offered by music and video programs disappears but you can use vpn with ip from germany and when you register you can access the content, after registration and login you do not need to use vpn, but the bad news is that the developer in charge of deezloader never update it to support flac because there is another program deezer downloader by bigboot written in java that is more complete and update it to 1.4.9 and if you added support to flac on pc, mac, linux and android

**Comment by svbnet** [comment]
It could be - they can issue a request and people will take it down for fear of the consequences. Of course, Athame is now a base that plugins can be connected to but I think in a lot of people's eyes it could be seen as a tool for enabling piracy. Even so, third-party sites still host copies of DVDShrink so there must be a line or threshold deciding if it's a significant threat or if it's not.
