### ISSUE TITLE
Error Downloading Album TIDAL

### ISSUE THREAD

**Issue by Ant4rez** [svbnet/Athame#139]
What is your OS version?

Windows 10 64 Bits

Have you deleted your config file? Paste the path `%appdata%\Athame` into the Windows Explorer address bar then delete the `settings.json` file.

Yes

Have you ensured you are using the latest version?

Yes Athame 0.4.6.1

Can you play back the track or collection on the web?

Yes https://listen.tidal.com/album/31415778

![imagen](https://i.imgur.com/T6mp97X.png)

EDIT: Now i can download it, but i don't do anything, that is weird.

**Comment by fabriccioguzman** [comment]
Currently the tidal for athame plugin does not support artist url
but it is possible that the album failed you for two reasons, 1 (confirmed) 8the dev of tidal and wimp learned of the security hole that the web player had because in the last days they have made changes in the web and they repaired it 2: bad Internet connection

**Comment by Ant4rez** [comment]
Ohh, but if i don't download it from the website, how i download it?

**Comment by FatKiwi** [comment]
Artist url not supported yet. Even the screenshot says it to you. Close it.
