### ISSUE TITLE
[Tidal] Suggestion: Fallback to MP3 320, instead of M4A 96 when FLAC is not available.

### ISSUE THREAD

**Issue by FatKiwi** [svbnet/Athame#32]
Some albums are only encoded in 96kbps m4a only (and since 2017 in 320kbps mp3)

Example Album ID: 17306123
Only downloads as 96kbps m4a, no matter what quality is set in app. But Chrome can fetch 320kbps mp3.

So maybe you should do a check if quality 17 (mp3 320) exist in API to prefer it, instead of quality 36 (m4a 96).

I think they're secretly replacing the "no HiFi" releases from 96 m4a to 320 mp3

**Comment by svbnet** [comment]
Once again it's Tidal being weird. Athame essentially "acts" as the desktop client in order to download MQA FLAC files, but for some reason in this instance the Tidal server gives a 320k MP3 URL to a web client session that requests it, but a 96k M4A URL to a desktop client session. Unfortunately I don't have a good fix so hopefully this isn't the case for many albums.
