### ISSUE TITLE
Does not define tracks of album, if at least one track is not available for listening. (Tidal)

### ISSUE THREAD

**Issue by Refelinux** [svbnet/Athame#44]
Thank You for amazing program. You made just BEST WAY for me! One nuance. The program gives an error if I want to download an album in which at least one track for streaming is not available. I tried with different albums.

http://imgur.com/DLUHTAa

for example this album - https://listen.tidal.com/album/75199043
It does not have a lot of tracks, but there are available some tracks. 

Thank You for your attention. Best Regards!

**Comment by fabriccioguzman** [comment]
That has solution, but it is temporary, what you have to do is copy the link of each track and paste it into the program and download it and it is saved in the same folder of the album, to me it has happened, what happens is the program Athame detects all the music until it is blocked by region or not available and downloads in order, but since it is not available gives that error, and not joe not program it to skip that music that is not available and is very Common this type of problem

**Comment by svbnet** [comment]
Looks like an oversight in the new Tidal plugin implementation, oops

**Comment by Refelinux** [comment]
I think the best way right now it's makes playlist with available tracks, and just download album without any problems.

**Comment by svbnet** [comment]
Fixed, just download https://github.com/svbnet/AthamePlugin.Tidal/releases/tag/2.1 and extract it into the plugins directory, replacing the "Tidal" folder
