### ISSUE TITLE
Can I remove the "Respect the artists! Pay for music when you can! Downloaded with Athame" comment?

### ISSUE THREAD

**Issue by Rekrap13** [svbnet/Athame#81]
Can I remove the "Respect the artists! Pay for music when you can! Downloaded with Athame" comment?It won't go away when I go to put it on my phone through iTunes

**Comment by fabriccioguzman** [comment]
Yes, you can delete it with Mp3tag, you right click mp3tag and wait and right click on the attachment and extended tags and modify it
svbnet will not delete that comment since he did it so we can buy the music instead of pirating it

**Comment by jonaaa20** [comment]
^ just saying that MP3Tag supports FLAC and even MKV files, not just MP3s!

**Comment by redreadnut** [comment]
Who can compile latest version without those words?

**Comment by UserForTheOnlyTopic** [comment]
to all with the weird ask: you should respect the work of @svbnet, he has done much for you and he just added some info that also advertises his product and you want remove it. Isn't it impudent? No? It's very disrespectful. I hope people who can do it have respect to @svbnet and won't do as some people here ask.

**Comment by smiba** [comment]
If you want it out so badly go remove it from the code and recompile it yourself, it shouldn't take more then a couple of minutes.

If you speedrun it you can get it down in one minute probably even

**Comment by redreadnut** [comment]
@smiba Ara, we are here to help each other, no? For you to know, you are not obliged to help me or someone else here. I think the "clean" version should be for those who don't give a shit how to compile and don't have VS and don't want to dwnl & install it only for removing one sentence.
get it down in one minute probably even? So you, instead of typing those message, could actually help, but no of course. It's better to critisize me and write obvious things.
And who told you that I'm not respecting Joe? I respect him more that those russians bitches making shitty and buggy analogs of Athame. They can only boast and not sharing to other people, and think that they investigated America by creating those shit but actually they just copied Joe's work. That's what I can say to you.

**Comment by fabriccioguzman** [comment]
@redreadnut  recommend you say obscene words, it's bad that you say those things

**Comment by redreadnut** [comment]
@fabriccioguzman 
Damn, Guzman you just everywhere <_<

**Comment by fabriccioguzman** [comment]
@redreadnut I want to be a collaborator of this project I am everywhere

**Comment by ThePlayingGoblin** [comment]
@Rekrap13 Please close this issue. This is stupid. If you people don't like the tags, as @fabriccioguzman said use Mp3Tag. By generating this kind of heat, more people are likely to find it on google, and if we get the wrong person to use this tool, they can contact google or tidal to shut down this project, and you can say goodbye to your hopes of seeing a deezer or spotify plugin.
