### ISSUE TITLE
install on linux

### ISSUE THREAD

**Issue by abdiasriver** [svbnet/Athame#84]
This is a great plugin, the best i found it,,but the question is

can i install this plugin on linux?  i have arch

please show me the instructions...and thanks again for this awesome plugin

**Comment by UserForTheOnlyTopic** [comment]
"I am also currently considering a cross-platform interface (since WinForms is incredibly buggy on non-Windows platforms), but again this is just a consideration as writing a command-line interface would take time away from porting it to WPF." @svbnet 
You can use a virtual machine for the app if you like unix stuff.

**Comment by abdiasriver** [comment]
thank you friend, I'll install it from an emulator aver if it works...

**Comment by svbnet** [comment]
Other platforms are currently not supported at the moment, unfortunately. Some people have had success with WINE, though.
